# Scientific python: NumPy, SciPy and Matplotlib

## Supplemental Exercises to Lecture 2

  * Learn what NumPy arrays are
  * Learn basic array manipulations
  * Learn what vectorial code is
  * Quick overview of SciPy
  * Learn how to do a simple 2D plot and decorate it
  * Learn how to combine plots into a single figure

## Further reading
* http://scipy-lectures.org
* https://www.nature.com/articles/s41586-020-2649-2
* https://numpy.org/doc/

# Supplemental exercises
The following is supplimental if you would like more practice on what you have covered:


In [1]:
# Import pybryt which will be used to check your solutions against reference solutions
#%pip install pybryt
import pybryt
from reflecture import pybryt_reference
# Convention: Import numpy and alias/rename it as np
import numpy as np

### Exercise 2.20
We are going to start with an array using the arange method. 

Use arange to create an array with 20 elements. It should be named `arr`.

In [2]:
## Solution...
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
## do not change any of the following code. It is used to check your work and provide feedback.
with pybryt.check(pybryt_reference(2, 201)):
    print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
REFERENCE: exercise-2_201
SATISFIED: True
MESSAGES:
  - SUCCESS: Array `a` checked: OK


Create a new array called `arr54` formed from the array `arr` we have just created. Using reshape, turn it into a 4 by 5 array.

In [4]:
## Solution...
arr54 = arr.reshape(4,5)
print(arr54)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [5]:
# do not change any of the following code. It is used to check your work and provide feedback.
with pybryt.check(pybryt_reference(2, 202)):
    print(arr54)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
REFERENCE: exercise-2_202
SATISFIED: True
MESSAGES:
  - SUCCESS: Array `arr54` checked: OK


Now change all the elements in the 3rd row of `arr54` to zero.

In [6]:
## Solution...
arr54[2, :] = 0
print(arr54)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]]


In [7]:
# do not change any of the following code. It is used to check your work and provide feedback.
with pybryt.check(pybryt_reference(2, 203)):
    print(arr54)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]]
REFERENCE: exercise-2_203
SATISFIED: True
MESSAGES:
  - SUCCESS: Array `arr54` checked: OK


Next let us reverse the order of the columns, as save the result in a new array called `arr54_flipped`. You can use `np.flip` or array slicing to achieve this.

In [8]:
## Solution...
arr54_flipped = arr54[::, ::-1]
print(arr54_flipped)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [ 0  0  0  0  0]
 [19 18 17 16 15]]


In [9]:
# do not change any of the following code. It is used to check your work and provide feedback.
with pybryt.check(pybryt_reference(2, 204)):
    print(arr54_flipped)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [ 0  0  0  0  0]
 [19 18 17 16 15]]
REFERENCE: exercise-2_204
SATISFIED: True
MESSAGES:
  - SUCCESS: Array `arr54` checked: OK
